-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 22:25:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notitas_dh_nelson
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `notitas_dh_nelson` ;

-- -----------------------------------------------------
-- Schema notitas_dh_nelson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notitas_dh_nelson` DEFAULT CHARACTER SET utf8 ;
USE `notitas_dh_nelson` ;

-- -----------------------------------------------------
-- Table `notitas_dh_nelson`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notitas_dh_nelson`.`notes` ;

CREATE TABLE IF NOT EXISTS `notitas_dh_nelson`.`notes` (
  `id_note` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` TEXT(300) NULL,
  PRIMARY KEY (`id_note`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
